### ISSUE TITLE
Unable to install app on device

### ISSUE THREAD

**Issue by boxfish** [Azure-Samples/Cognitive-Speech-STT-iOS#11]
- When pushing the app to an iPad, Xcode complains "The certificate used to sign "APP_NAME" has either expired or has been revoked. An updated certificate is required to sign and install the application." 
- After removing the SpeechSDK.framework from the "Embedded Binaries", the app can be installed on the same device, but the app immediately crashes, complaining "Image not found"

**Comment by jasonvomsft** [comment]
Are you signing with a valid certificate?

**Comment by priyaravi20** [comment]
Resolving this as a non-issue.
