### ISSUE TITLE
The sample app doesn't work on iOS 10

### ISSUE THREAD

**Issue by phongcao** [Azure-Samples/Cognitive-Speech-STT-iOS#14]
There are two issues:
1. **NSMicrophoneUsageDescription** is missing from the Info.plist file.
2. Layout issues: 'Start' button isn't aligned, missing the main text area when testing on both simulator and iPhone6/6s.

**Comment by priyaravi20** [comment]
Thanks for letting us know. We will be addressing this in our future update.

Priya Rajan
Microsoft
