### ISSUE TITLE
ObjC “namespacing” is missing

### ISSUE THREAD

**Issue by JanX2** [Azure-Samples/Cognitive-Speech-STT-iOS#16]
The classes in the API are not prefixed as per Apple recommendations. This can lead to naming collisions. Especially in larger projects. 

For example, naming a class `Preferences` will cause problems, if the project already has a class called `Preferences`. Naming it `CSSSTPreferences` would resolve this.

**Comment by priyaravi20** [comment]
Thanks for bringing this up. We will add this to a future update.

Priya Rajan
Microsoft
