### ISSUE TITLE
Using the Mac OSX SDK?

### ISSUE THREAD

**Issue by margaretmz** [Azure-Samples/Cognitive-Speech-STT-iOS#2]
_From @joacimstahl on April 26, 2016 15:12_

Trying to build an OSX app with the Mac OSX SDK SpeechSDK.framework, however the build fails with:

`/Contents/Frameworks/SpeechSDK.framework/Versions/A: No such file or directory
Command /usr/bin/codesign failed with exit code 1`

Any ideas?

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#59_

**Comment by margaretmz** [comment]
_From @dmiller235623 on May 2, 2016 7:43_

the privacy notice had me so freaked out.. I wont mess with it until I'm
guaranteed people are using these services legit... I envision holo lens

**Comment by priyaravi20** [comment]
CLosing as per previous comment.
