### ISSUE TITLE
Crash in WebSocketMessageFormat::Type

### ISSUE THREAD

**Issue by atticus** [Azure-Samples/Cognitive-Speech-STT-iOS#22]
I've been experiencing occasional crashes in WebSocketMessageFormat::Type. The library works well most of the time, but I get this crash at the same line every few days or so.

`EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x0000000103800000`

Crashed: Thread
0  SpeechSDK                      0x100d09584 WSRequest::SendMessage(Bing::Speech::WebSocketMessageFormat::Type) + 224
1  SpeechSDK                      0x100ce72f0 Bing::Speech::WebSocketChannel::SendNextMessage() + 288
2  SpeechSDK                      0x100ce8454 Bing::Speech::WebSocketChannel::OnHandshakeComplete(Bing::Speech::IHttpWebSocket&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, Bing::Speech::IHttpResponse&) + 536
3  SpeechSDK                      0x100d09700 WSRequest::OnHeadersAvailable(Bing::Speech::IHttpResponse&) + 192
4  SpeechSDK                      0x100d08d98 Request::Worker() + 264
5  SpeechSDK                      0x100d09fac Request::S_Worker(void*) + 44
6  SpeechSDK                      0x100d10f04 TPStart(void*) + 32
7  libsystem_pthread.dylib        0x18918d850 <redacted> + 240
8  libsystem_pthread.dylib        0x18918d760 _pthread_start + 282
9  libsystem_pthread.dylib        0x18918ad94 thread_start + 4

**Comment by CavanLife** [comment]
We are going to working with Microsoft，but， the SDK has too many crashes,  we are not going to use again！！

**Comment by priyaravi20** [comment]
We are currently investigating this issue.  Can you please attach the logs to debug further.

Priya Rajan
Microsoft

**Comment by atticus** [comment]
I haven't seen the issue for a while, so perhaps it's been resolved. Unfortunately I don't have any logs beyond what I added above.

**Comment by priyaravi20** [comment]
Yes this has been resolved.
