### ISSUE TITLE
Wifi after switching to 4G, dataClinet translation is invalid！！！

### ISSUE THREAD

**Issue by CavanLife** [Azure-Samples/Cognitive-Speech-STT-iOS#24]
Wifi after switching to 4G, dataClinet translation is invalid, even if the re-initialization！！！

The following is the log output after switching：

originating error 0x80070057
originating error 0x8000ffff
Failed to initiate async send operation, hr=8000FFFF
web socket message delivery failed, hr=8000FFFF
Closing web socket channel
CU Client connection dropped
ConnectionStateChanged
Message: 'audio.stream.body' has 4 remaining transmit attempts.
Retrying message, name='audio.stream.body'
Initiating websocket connection. m_connection=0x1700ba538 host=websockets.platform.bing.com port=443
originating error 0x80004005
originating error 0x80004005

@bursteg @dlfu @selvasingh @azureopensource @azurecompliance3

**Comment by CavanLife** [comment]
No one to answer the question?

**Comment by priyaravi20** [comment]
Can you send the entire log to debug this further.

Priya Rajan
Microsoft

**Comment by CavanLife** [comment]
LanguageGeneration OK
2017-05-03 09:25:52.711578+0800 HWSpeech[2934:1060903] **** partial result ****你
Received message: 'audio.stream.response'
Response request id: '1f4ec444-93b8-d537-6336-c31ca2e3273d'
Response impression: 'eb88c6af-0380-49ae-21f1-692818c5572c'

LanguageGeneration OK
2017-05-03 09:25:52.726916+0800 HWSpeech[2934:1060903] **** partial result ****因为


originating error 0x80070057
originating error 0x8000ffff
Failed to initiate async send operation, hr=8000FFFF
web socket message delivery failed, hr=8000FFFF
Closing web socket channel
CU Client connection dropped
ConnectionStateChanged
Message: 'audio.stream.body' has 4 remaining transmit attempts.
Retrying message, name='audio.stream.body'
Initiating websocket connection. m_connection=0x1740bea98 host=websockets.platform.bing.com port=443
originating error 0x80004005
originating error 0x80004005

**Comment by priyaravi20** [comment]
Please retry with latest updates. Closing this for now.
