### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by atticus** [Azure-Samples/Cognitive-Speech-STT-iOS#25]
Is there any plan for IPv6 support? Some cell carriers like T-Mobile are IPv6-only, and so this library won't work.

**Comment by shun-sato93** [comment]
it's written in the review guidelines that ipv6 support is required .

[https://developer.apple.com/app-store/review/guidelines/](https://developer.apple.com/app-store/review/guidelines/)
> 2.5.5
> We will be reviewing on an IPv6 network, so if your app isn’t compatible with the IPv6 addressing, it may fail during review.

so actually we can't use this library for iOS app currently.

**Comment by CavanLife** [comment]
China mobile's 4G network start cognitive services failed, is the cause of IPv6?
@atticus @shun-sato93

**Comment by atticus** [comment]
It's possible. I know in the US at least one carrier (T-Mobile) only supports IPv6. Many of them still support IPv4 for now, but probably won't forever.

**Comment by priyaravi20** [comment]
The published sample works with all carriers. Please send logs to investigate further.

**Comment by atticus** [comment]
I will try to find one of our users on T-Mobile to get logs, but I know that for several users on T-Mobile the SDK fails every time. I assume that since @jasonvomsft stated that the SDK doesn't support IPv6 in #13 , and that T-Mobile only supports IPv6 (not IPv4), that's the reason. If the SDK is supposed to support IPv6 I can try to get more logs to see what's going on.

**Comment by priyaravi20** [comment]
This has been added in the last update.
