### ISSUE TITLE
Crash！！！

### ISSUE THREAD

**Issue by CavanLife** [Azure-Samples/Cognitive-Speech-STT-iOS#26]
Initiating websocket connection. m_connection=0x1740a2898 host=websockets.platform.bing.com port=443
originating error 0x8e200001
Authorization token hr 0 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiMGIyMjBmZWRmNGNiNDY3NGEwZGYzNzU5NmUzNzU1OGQiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDkyNzQ4MzgzfQ.o6fQqTORAFEzFSpGsCrMLHelMVz1siNxzd_HDtSMT10' 
Waiting for connection/send completion.
WebSocket closed unexpectedly, status: 0
Closing web socket channel
CU Client connection dropped
ConnectionStateChanged
WSRequest

Initiating websocket connection. m_connection=0x1740a2898 host=websockets.platform.bing.com port=443
originating error 0x8000ffff
originating error 0x8e200003
Authorization token hr 0 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiMGIyMjBmZWRmNGNiNDY3NGEwZGYzNzU5NmUzNzU1OGQiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDkyNzQ4MzgzfQ.o6fQqTORAFEzFSpGsCrMLHelMVz1siNxzd_HDtSMT10' 
Waiting for connection/send completion.
Sending audio stream endpoint, requestId='e21883eb-535f-9801-0af6-8cdf49a3f1ff'
Waiting for connection/send completion.
Sent audio stream endpoint, requestId='e21883eb-535f-9801-0af6-8cdf49a3f1ff'
WebSocket closed unexpectedly, status: 0
Closing web socket channel
CU Client connection dropped
ConnectionStateChanged
WSRequest

Upgrade request returned with HTTP status code: 101.
Web socket handshake completed
CU Client connected
Adding requestId: '0cff32b58991cdefbdeec5b07c0b529a' for 'text/cu.client.context'
Subscribing request [0cff32b58991cdefbdeec5b07c0b529a]
Initiating websocket connection. m_connection=0x1740a2898 host=websockets.platform.bing.com port=443
Authorization token hr 0 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiMGIyMjBmZWRmNGNiNDY3NGEwZGYzNzU5NmUzNzU1OGQiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDkyNzQ4MzgzfQ.o6fQqTORAFEzFSpGsCrMLHelMVz1siNxzd_HDtSMT10' 
Waiting for connection/send completion.
ConnectionStateChanged
HWSpeech(1836,0x16dfc3000) malloc: *** error for object 0x10091ba00: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

---------------------------------

please help me...

---------------------------------

The number of this SDK  crashes, the most in the SDKs I ever used...

**Comment by priyaravi20** [comment]
Can you please send us the call stack to help debug the issue further.

**Comment by CavanLife** [comment]
when you switch your mobile network to very bad network, then initiate a DataClient continually, it will crash!!

you can try it by yourself!

**Comment by priyaravi20** [comment]
Please retry with the latest updates which handles network issues.
