### ISSUE TITLE
Apple Mach-O Linker (id).Error - linker command failed with exit code (use -v to see invocation)

### ISSUE THREAD

**Issue by RiyasMeeran** [Azure-Samples/Cognitive-Speech-STT-iOS#27]
Getting this error when i added SpeechSDK.framework in a new project and try to run on iPhone 6 device.

![h_fullsize_distr](https://cloud.githubusercontent.com/assets/16999176/26549763/2b7a30c8-4498-11e7-949b-0ef136b2aa87.png)

I follow steps in this link https://github.com/Azure-Samples/Cognitive-Speech-STT-ios. Create new project add SpeechSDK.framework from Azure-Samples/Cognitive-Speech-STT-iOS/iPhoneOS/SpeechSDK.framework. then build failed.

How to fix this?

**Comment by priyaravi20** [comment]
Please try the latest update.
