### ISSUE TITLE
how to i get mic volume level?

### ISSUE THREAD

**Issue by Jagadeesh-Govindaraj** [Azure-Samples/Cognitive-Speech-STT-iOS#29]
i writing a conversation application using this sdk, it went well but i need a waves animation when user interact to the system.can you expose the mic volume in your api responses be like

`response.micLevel`

it would be a more helpful .

**Comment by raaaar** [comment]
There's the 'onMicrophoneStatus' callback that's invoked with the 'recording' argument set to true, when the mic is being used. This should be enough to enable your scenario.
