### ISSUE TITLE
Is there a recommended way to send multiple audio files at the same time?

### ISSUE THREAD

**Issue by cerupcat** [Azure-Samples/Cognitive-Speech-STT-iOS#30]
In order to speed up transcription, I'm splitting a single file into multiple and would like to send them in parallel. Do we have to open multiple websockets/clients in order to send in parallel?

**Comment by priyaravi20** [comment]
Hi cerupcat - We do not support parallel recognition at the present moment. With the latest API we do not support upto 10 min of audio.

**Comment by cerupcat** [comment]
Thanks @priyaravi20. That's good to know. Since my transcription needs are from pre-recorded audio, I'm looking to transcribe in faster than real-time and parallelising should help. I look forward to seeing if this is supported in the future.

**Comment by cerupcat** [comment]
Would the REST API be a solution for now?

**Comment by priyaravi20** [comment]
REST API is available but there is a restriction of 15 seconds of audio and given its a one shot reco latency might be an issue. ios SDK uses websockets which sends intermediate results hence its a better option for longer audio recos.
