### ISSUE TITLE
Enable BitCode

### ISSUE THREAD

**Issue by hakim-ali** [Azure-Samples/Cognitive-Speech-STT-iOS#34]
Hi,
While using **SpeechSDK.framework** into swift project i am getting enable bitcode issue. Kindly guide me how i can resolve this issue.

**Error Message**
Showing Recent Messages
ld: '/Users/dsg226/Downloads/SpeechRecognitionExample-master/SpeechSDK.framework/SpeechSDK' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by raaaar** [comment]
Is disabling the bitcode for your app an option? 

https://stackoverflow.com/questions/32947236/how-to-enable-or-disable-bitcode-for-specific-library-or-sdk-in-xcode-project
