### ISSUE TITLE
Can't run on simulator

### ISSUE THREAD

**Issue by jpanchal** [Azure-Samples/Cognitive-Speech-STT-iOS#5]
I have referenced correct framework for simulator and I still get following error, it does build successfully!:

dyld: Library not loaded: @rpath/SpeechSDK.framework/SpeechSDK
  Referenced from: /Users/jigp/Library/Developer/CoreSimulator/Devices/B4D621DA-568F-46D7-B216-47272D1057D1/data/Containers/Bundle/Application/B9D7966C-15BB-469A-A421-0A8F1100BBC8/FreeformCapture.app/FreeformCapture
  Reason: no suitable image found.  Did find:
    /Users/jigp/Library/Developer/CoreSimulator/Devices/B4D621DA-568F-46D7-B216-47272D1057D1/data/Containers/Bundle/Application/B9D7966C-15BB-469A-A421-0A8F1100BBC8/FreeformCapture.app/Frameworks/SpeechSDK.framework/SpeechSDK: **no matching architecture in universal wrapper**

**Comment by xsywayne11** [comment]
it works for me: Add "$(inherited)@executable_path/Frameworks" to your Runpath Search Paths on your Xcode target Build settings.

**Comment by jasonvomsft** [comment]
@jpanchal  did @xsywayne11 suggestion address your problem?

**Comment by priyaravi20** [comment]
Closing as per comment above.
